#-----------------------------------------
# This script defines a reusable dataframe
# of amplifier names, their brands, and
# a qualitative definition of their gain
# structure/type
#-----------------------------------------

#-----------------------------------------
# Author: Trent Henderson, 8 December 2022
#-----------------------------------------

metadata <- data.frame(id = c("Neural DSP Cory Wong 1", "Neural DSP Cory Wong 2", "Neural DSP Cory Wong 3",
                              "Neural DSP Fortin Nameless", "Neural DSP Fortin Cali Clean", "Neural DSP Fortin Cali Overdrive 1",
                              "Neural DSP Fortin Cali Overdrive 2", "Neural DSP Fortin NTS Clean", "Neural DSP Fortin NTS Overdrive",
                              "Neural DSP Gojira 1", "Neural DSP Gojira 2", "Neural DSP Gojira 3", "Neural DSP Nolly 1", "Neural DSP Nolly 2",
                              "Neural DSP Nolly 3", "Neural DSP Nolly 4", "Neural DSP Petrucci 1", "Neural DSP Petrucci 2",
                              "Neural DSP Petrucci 3", "Neural DSP Petrucci 4", "Neural DSP Plini 1", "Neural DSP Plini 2",
                              "Neural DSP Plini 3", "Neural DSP Rabea 1", "Neural DSP Rabea 2_6L6", "Neural DSP Rabea 2_EL34",
                              "Neural DSP Rabea 3_6L6", "Neural DSP Rabea 3_EL34", "Neural DSP Soldano Normal",
                              "Neural DSP Soldano Overdrive", "Neural DSP Tim Henson 1", "Neural DSP Tim Henson 2",
                              "Neural DSP Tim Henson 3", "Neural DSP Tone King Lead", "Neural DSP Tone King Rhythm",
                              "STL Tonality Will Putney 1_6L6", "STL Tonality Will Putney 1_EL34", "STL Tonality Will Putney 1_KT88",
                              "STL Tonality Will Putney 2_6L6", "STL Tonality Will Putney 2_EL34", "STL Tonality Will Putney 2_KT88",
                              "STL Tonality Will Putney 3_6L6", "STL Tonality Will Putney 3_EL34", "STL Tonality Will Putney 3_KT88",
                              "STL Tonality Will Putney 4_6L6", "STL Tonality Will Putney 4_EL34", "STL Tonality Will Putney 4_KT77",
                              "STL Tonality Will Putney 4_KT88",
                              "STL Tonality Andy James 1_6L6", "STL Tonality Andy James 1_EL34", "STL Tonality Andy James 1_KT88",
                              "STL Tonality Andy James 2_6L6", "STL Tonality Andy James 2_EL34", "STL Tonality Andy James 2_KT88",
                              "STL Tonality Andy James 3_Lo", "STL Tonality Andy James 3_Hi",
                              "STL Tonality Howard Benson 1", "STL Tonality Howard Benson 2_Clean", "STL Tonality Howard Benson 2_Lead",
                              "STL Tonality Howard Benson 3", "STL Tonality Howard Benson 4", "STL Tonality Howard Benson 5",
                              "STL Tonality Lasse Lammert 1", "STL Tonality Lasse Lammert 2", "STL Tonality Lasse Lammert 3",
                              "Neural DSP Abasi 1", "Neural DSP Abasi 2", "Neural DSP Abasi 3", "Neural DSP Omega Granophyre_6L6",
                              "Neural DSP Omega Granophyre_EL34", "Neural DSP Omega Granophyre_KT66")) %>%
  mutate(brand = ifelse(grepl("Neural", id), "Neural DSP", "STL Tonality")) %>%
  mutate(plugin = case_when(
          grepl("Cory", id)       ~ "Archetype: Cory Wong",
          grepl("Nameless", id)   ~ "Fortin Nameless",
          grepl("Gojira", id)     ~ "Archetype: Gojira",
          grepl("Nolly", id)      ~ "Archetype: Nolly",
          grepl("Plini", id)      ~ "Archetype: Plini",
          grepl("Henson", id)     ~ "Archetype: Tim Henson",
          grepl("Cali", id)       ~ "Fortin Cali Suite",
          grepl("NTS", id)        ~ "Fortin NTS Suite",
          grepl("Rabea", id)      ~ "Archetype: Rabea",
          grepl("Tone King", id)  ~ "Tone King Imperial MKII",
          grepl("Petrucci", id)   ~ "Archetype: Petrucci",
          grepl("Soldano", id)    ~ "Soldano SLO-100",
          grepl("Abasi", id)      ~ "Archetype: Abasi",
          grepl("Granophyre", id) ~ "Omega Ampworks Granophyre",
          grepl("Andy", id)       ~ "STL Tonality Andy James",
          grepl("Howard", id)     ~ "STL Tonality Howard Benson",
          grepl("Lasse", id)      ~ "STL Tonality Lasse Lammert",
          grepl("Putney", id)     ~ "STL Tonality Will Putney")) %>%
  mutate(amp_type = case_when(
    id == "Neural DSP Cory Wong 1"             ~ "Acoustic/Other",
    id == "Neural DSP Cory Wong 2"             ~ "Clean",
    id == "Neural DSP Cory Wong 3"             ~ "Low Gain",
    id == "Neural DSP Fortin Nameless"         ~ "High Gain",
    id == "Neural DSP Gojira 1"                ~ "Clean",
    id == "Neural DSP Gojira 2"                ~ "High Gain",
    id == "Neural DSP Gojira 3"                ~ "High Gain",
    id == "Neural DSP Nolly 1"                 ~ "Clean", # Crunch
    id == "Neural DSP Nolly 2"                 ~ "Mid Gain", # Crunch
    id == "Neural DSP Nolly 3"                 ~ "High Gain", # Rhythm
    id == "Neural DSP Nolly 4"                 ~ "High Gain", # Lead
    id == "Neural DSP Plini 1"                 ~ "Clean",
    id == "Neural DSP Plini 2"                 ~ "Mid Gain",
    id == "Neural DSP Plini 3"                 ~ "High Gain",
    id == "Neural DSP Tim Henson 1"            ~ "Acoustic/Other",
    id == "Neural DSP Tim Henson 2"            ~ "Low Gain",
    id == "Neural DSP Tim Henson 3"            ~ "Mid Gain",
    id == "STL Tonality Will Putney 1_6L6"     ~ "High Gain",
    id == "STL Tonality Will Putney 1_EL34"    ~ "High Gain",
    id == "STL Tonality Will Putney 1_KT88"    ~ "High Gain",
    id == "STL Tonality Will Putney 2_6L6"     ~ "High Gain",
    id == "STL Tonality Will Putney 2_EL34"    ~ "High Gain",
    id == "STL Tonality Will Putney 2_KT88"    ~ "High Gain",
    id == "STL Tonality Will Putney 3_6L6"     ~ "High Gain",
    id == "STL Tonality Will Putney 3_EL34"    ~ "High Gain",
    id == "STL Tonality Will Putney 3_KT88"    ~ "High Gain",
    id == "STL Tonality Will Putney 4_6L6"     ~ "High Gain",
    id == "STL Tonality Will Putney 4_EL34"    ~ "Mid Gain",
    id == "STL Tonality Will Putney 4_KT77"    ~ "Mid Gain",
    id == "STL Tonality Will Putney 4_KT88"    ~ "Mid Gain",
    id == "Neural DSP Fortin Cali Clean"       ~ "Clean",
    id == "Neural DSP Fortin Cali Overdrive 1" ~ "High Gain",
    id == "Neural DSP Fortin Cali Overdrive 2" ~ "High Gain",
    id == "Neural DSP Fortin NTS Clean"        ~ "Clean",
    id == "Neural DSP Fortin NTS Overdrive"    ~ "High Gain",
    id == "Neural DSP Petrucci 1"              ~ "Acoustic/Other",
    id == "Neural DSP Petrucci 2"              ~ "Clean",
    id == "Neural DSP Petrucci 3"              ~ "High Gain",
    id == "Neural DSP Petrucci 4"              ~ "High Gain",
    id == "Neural DSP Rabea 1"                 ~ "Clean",
    id == "Neural DSP Rabea 2_6L6"             ~ "High Gain",
    id == "Neural DSP Rabea 2_EL34"            ~ "High Gain",
    id == "Neural DSP Rabea 3_6L6"             ~ "High Gain",
    id == "Neural DSP Rabea 3_EL34"            ~ "High Gain",
    id == "Neural DSP Soldano Normal"          ~ "Clean",
    id == "Neural DSP Soldano Overdrive"       ~ "High Gain",
    id == "Neural DSP Tone King Lead"          ~ "Low Gain",
    id == "Neural DSP Tone King Rhythm"        ~ "Low Gain",
    id == "STL Tonality Andy James 1_6L6"      ~ "High Gain",
    id == "STL Tonality Andy James 1_EL34"     ~ "High Gain",
    id == "STL Tonality Andy James 1_KT88"     ~ "High Gain",
    id == "STL Tonality Andy James 2_6L6"      ~ "High Gain",
    id == "STL Tonality Andy James 2_EL34"     ~ "High Gain",
    id == "STL Tonality Andy James 2_KT88"     ~ "High Gain",
    id == "STL Tonality Andy James 3_Lo"       ~ "Clean",
    id == "STL Tonality Andy James 3_Hi"       ~ "Low Gain",
    id == "STL Tonality Howard Benson 1"       ~ "High Gain",
    id == "STL Tonality Howard Benson 2_Clean" ~ "Clean",
    id == "STL Tonality Howard Benson 2_Lead"  ~ "High Gain",
    id == "STL Tonality Howard Benson 3"       ~ "Mid Gain",
    id == "STL Tonality Howard Benson 4"       ~ "Clean",
    id == "STL Tonality Howard Benson 5"       ~ "Low Gain",
    id == "STL Tonality Lasse Lammert 1"       ~ "High Gain",
    id == "STL Tonality Lasse Lammert 2"       ~ "High Gain",
    id == "STL Tonality Lasse Lammert 3"       ~ "High Gain",
    id == "Neural DSP Abasi 1"                 ~ "Clean",
    id == "Neural DSP Abasi 2"                 ~ "High Gain",
    id == "Neural DSP Abasi 3"                 ~ "High Gain",
    id == "Neural DSP Omega Granophyre_6L6"    ~ "High Gain",
    id == "Neural DSP Omega Granophyre_EL34"   ~ "High Gain",
    id == "Neural DSP Omega Granophyre_KT66"   ~ "High Gain"))
